name: generate-help
on: [push]
jobs:
  compile_help:
    name: Build help file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Load help
      run: |
        ruby .github/bin/load_help.rb > help.csv
    - name: Upload help file
      uses: actions/upload-artifact@v2
      with:
        name: help-csv-file
        path: help.csv
  commit_help:
    name: Commit help
    needs: compile_help
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - uses: actions/download-artifact@v2
      with:
        name: help-csv-file
        path: _data
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Uploaded new help docs
