name: generate-help
on: [push]
jobs:
  compile_help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Load help
      run: |
        ruby .github/bin/load_help.rb > help.log
    - name: Upload help file
      uses: actions/upload-artifact@v2
      with:
        name: help-log-file
        path: help.log
