name: generate-help
on: [push]
jobs:
  load_help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Load help
      run: |
        ruby .github/bin/load_help.rb > output.log
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-log-file
        path: output.log
